FROM node:18-slim

RUN apt update && apt install -y \
    git gpg gnupg gpg-agent socat \
    ca-certificates \
    zsh \
    curl \
    wget \
    fonts-powerline \
    procps

RUN npm i -g @nestjs/cli@10.1.7

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app


COPY --chown=node:node package*.json .

RUN npm install

COPY --chown=node:node . .


RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t https://github.com/romkatv/powerlevel10k \
    -p git \
    -p git-flow \
    -p https://github.com/zdharma-continuum/fast-syntax-highlighting \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -a 'export TERM=xterm-256color'

RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc && \
    echo 'HISTFILE=/home/node/zsh/.zsh_history' >> ~/.zshrc 


CMD [".docker/start.sh"]
