FROM node:18-slim as testing

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY --chown=node:node . .

RUN npm run build

ENV NODE_ENV=prod

CMD [ "npm", "run", "start:prod" ]

